configs:
  use: 'default'
  name: 'hitachi-vantara-qa-environment-ubuntu-16.04'
  box:
    username: ''
    password: ''
  default:
    test:
      major: '7.1'
      minor: '7.1.0.26-212'
    base_os: 'ubuntu/xenial64'
    disk_size: '20GB'
    os_version: '16.04'
    public_ip: '1.6.0.4'
    port: '8080'
    java_version: '8'
    cpus: '2'
    memory: '8192'
    vram: '256'
    clipboard: 'bidirectional'
    natdnshostresolver1: 'on'
    natdnsproxy1: 'on'
