configs:
  use: 'default'
  name: 'VM_NAME'
  box:
    username: ''
    password: ''
  default:
    test:
      major: 'VM_TEST_MAJOR_VERSION'
      minor: 'VM_TEST_MINOR_VERSION'
    base_os: 'VM_BASE_OS'
    box_version: 'VM_BOX_VERSION'
    disk_size: '20GB'
    os_version: 'VM_OS_VERSION'
    public_ip: 'VM_IP_ADDRESS'
    port: '8080'
    java_version: '8'
    cpus: '2'
    memory: '8192'
    vram: '256'
    clipboard: 'bidirectional'
    natdnshostresolver1: 'on'
    natdnsproxy1: 'on'
