configs:
  use: 'default'
  name: 'hitachi-vantara-qa-environment-ubuntu-18.04'
  box:
    username: ''
    password: ''
  default:
    test:
      major: '7.1'
      minor: '7.1.0.26-212'
    patch_version_override_path: ''
    box_version: '20190621.0.0'
    disk_size: '20GB'
    os_version: '18.04'
    public_ip: '1.8.0.4'
    port: '8080'
    java_version: '8'
    cpus: '2'
    memory: '8192'
    vram: '256'
    clipboard: 'bidirectional'
    natdnshostresolver1: 'on'
    natdnsproxy1: 'on'
