configs:
  use: 'default'
  name: 'hitachi-vantara-qa-environment-ubuntu-18.04'
  box:
    username: ''
    password: ''
  default:
    test:
      major: '8.3'
      minor: '8.3.0.1-435'
    base_os: 'ubuntu/bionic64'
    disk_size: '20GB'
    os_version: '18.04'
    public_ip: '1.8.0.4'
    port: '8080'
    java_version: '8'
    cpus: '2'
    memory: '8192'
    vram: '256'
    clipboard: 'bidirectional'
    natdnshostresolver1: 'on'
    natdnsproxy1: 'on'
