configs:
    use: 'default'
    chrome: 'C:\\Users\\jeruiz\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe'
    name: 'BISERVER-13804-ubuntu-server-18-8.3-ga-silent'
    default:
        public_ip: '8.3.0.0'
        port: 8080
